#!/usr/bin/env node
//
// IndexNow ping for dvt.dev (DVT-2995). Diffs a "previous" sitemap against a
// freshly built "next" sitemap and POSTs the set of changed URLs to the
// IndexNow API, so Bing/Yandex/etc. pick up new/changed/deleted pages faster
// than organic recrawl.
//
// Usage:
//   node scripts/indexnow-ping.mjs --prev <path> --next <path> [--full] [--dry-run]
//
// Modes:
//   diff (default)  submit URLs that are new in --next, whose <lastmod>
//                    changed between --prev/--next (including lastmod
//                    appearing/disappearing), or that were removed from
//                    --next (deleted pages — IndexNow wants those too, so
//                    engines recrawl and see the 404). --prev is required.
//   --full           submit every URL in --next, ignoring --prev entirely.
//                     Used for the one-time initial full submission via
//                     workflow_dispatch.
//   --dry-run        print the would-be submission list and count, POST
//                     nothing, exit 0. Also writes `count=<n>` to
//                     $GITHUB_OUTPUT when that env var is set, so the
//                     workflow can decide whether to wait for deploy.
//
// The sitemap files are machine-generated by @astrojs/sitemap, so a small
// regex-based parser is used instead of pulling in an XML dependency.
//
// Zero external dependencies: Node 22+ built-ins only (global fetch).
//

import { readFileSync, appendFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const HOST = 'dvt.dev';

// The IndexNow key is public by protocol design — engines fetch it from
// KEY_LOCATION to verify the ping is authorized, so there's no secrecy to
// protect here. It's derived from the committed key file (rather than
// hardcoded as a literal) to avoid a high-entropy string that trips secret
// scanners, and to keep the filename and key content defined in one place.
function findKey() {
  const publicDir = fileURLToPath(new URL('../public/', import.meta.url));
  const matches = readdirSync(publicDir).filter((name) => /^[0-9a-f]{8,128}\.txt$/.test(name));

  if (matches.length === 0) {
    console.error(`ERROR: no IndexNow key file found in ${publicDir} (expected <hex>.txt)`);
    process.exit(1);
  }
  if (matches.length > 1) {
    console.error(`ERROR: multiple IndexNow key files found in ${publicDir}: ${matches.join(', ')}`);
    process.exit(1);
  }

  return matches[0].slice(0, -'.txt'.length);
}

const KEY = findKey();
const KEY_LOCATION = `https://${HOST}/${KEY}.txt`;
const INDEXNOW_URL = 'https://api.indexnow.org/indexnow';
const CHUNK_SIZE = 10_000;
const RETRY_DELAY_MS = 10_000;

function parseArgs(argv) {
  const args = { full: false, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--prev') args.prev = argv[++i];
    else if (arg === '--next') args.next = argv[++i];
    else if (arg === '--full') args.full = true;
    else if (arg === '--dry-run') args.dryRun = true;
    else {
      console.error(`unrecognized argument: ${arg}`);
      process.exit(1);
    }
  }
  return args;
}

/**
 * Minimal sitemap parser: returns a Map of loc -> lastmod (or null when a
 * <url> entry has no <lastmod>). Throws if the root element isn't <urlset>
 * — except when `lenient` is set, in which case it returns null instead, so
 * callers can treat an unparseable file as "skip" rather than fatal.
 */
function parseSitemap(path, { lenient = false } = {}) {
  const xml = readFileSync(path, 'utf8');

  if (!/<urlset[\s>]/.test(xml)) {
    if (lenient) return null;
    console.error(`ERROR: ${path} does not contain a <urlset> root element — not a sitemap file`);
    process.exit(1);
  }

  const urls = new Map();
  const urlBlockRe = /<url>(.*?)<\/url>/gs;
  for (const [, block] of xml.matchAll(urlBlockRe)) {
    const locMatch = block.match(/<loc>(.*?)<\/loc>/s);
    if (!locMatch) continue;
    const loc = locMatch[1].trim();
    const lastmodMatch = block.match(/<lastmod>(.*?)<\/lastmod>/s);
    urls.set(loc, lastmodMatch ? lastmodMatch[1].trim() : null);
  }
  return urls;
}

/** Diff mode: new URLs, URLs whose lastmod changed (including appear/disappear), and deleted URLs. */
function diffUrls(prevUrls, nextUrls) {
  const changed = [];
  for (const [loc, lastmod] of nextUrls) {
    if (!prevUrls.has(loc)) {
      changed.push(loc); // new
    } else if (prevUrls.get(loc) !== lastmod) {
      changed.push(loc); // lastmod changed
    }
  }
  for (const loc of prevUrls.keys()) {
    if (!nextUrls.has(loc)) {
      changed.push(loc); // deleted
    }
  }
  return changed;
}

function chunk(array, size) {
  const chunks = [];
  for (let i = 0; i < array.length; i += size) {
    chunks.push(array.slice(i, i + size));
  }
  return chunks;
}

async function postChunk(urlList) {
  const body = JSON.stringify({
    host: HOST,
    key: KEY,
    keyLocation: KEY_LOCATION,
    urlList,
  });

  const attempt = async () => {
    try {
      const res = await fetch(INDEXNOW_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json; charset=utf-8' },
        body,
      });
      return { ok: true, res };
    } catch (err) {
      return { ok: false, err };
    }
  };

  let result = await attempt();

  // 429 (rate limit) is transient like 5xx — retry, then warn; never red.
  const isRetryable = (r) => !r.ok || r.res.status >= 500 || r.res.status === 429;

  if (isRetryable(result)) {
    const reason = result.ok ? `HTTP ${result.res.status}` : result.err.message;
    console.log(`IndexNow POST failed transiently (${reason}); retrying once in ${RETRY_DELAY_MS / 1000}s`);
    await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
    result = await attempt();
  }

  if (!result.ok) {
    console.log(`::warning::IndexNow POST failed after retry: ${result.err.message}`);
    return;
  }

  const { res } = result;
  if (res.status === 200 || res.status === 202) {
    console.log(`IndexNow POST succeeded: ${res.status} (${urlList.length} URLs)`);
    return;
  }

  if (res.status >= 500 || res.status === 429) {
    console.log(`::warning::IndexNow POST failed after retry: HTTP ${res.status}`);
    return;
  }

  // 4xx: a config bug (bad key/format) — loud and fatal.
  const text = await res.text().catch(() => '');
  console.error(`::error::IndexNow POST rejected with HTTP ${res.status}: ${text}`);
  process.exit(1);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (!args.next) {
    console.error('missing required --next <path>');
    process.exit(1);
  }
  if (!args.full && !args.prev) {
    console.error('missing required --prev <path> (or pass --full)');
    process.exit(1);
  }

  const nextUrls = parseSitemap(args.next);

  let submitUrls;
  if (args.full) {
    submitUrls = [...nextUrls.keys()];
    console.log(`full mode: submitting all ${submitUrls.length} URLs from ${args.next}`);
  } else {
    // A 200 response carrying non-sitemap HTML (e.g. a CF interstitial)
    // passes the workflow's `curl -fsS` check upstream, so treat an
    // unparseable --prev as a transient snapshot failure, not a build bug:
    // warn and skip the ping rather than redding main. An unparseable
    // --next is always fatal — that's this push's own build output.
    const prevUrls = parseSitemap(args.prev, { lenient: true });
    if (prevUrls === null) {
      console.log(`::warning::prev sitemap unparseable — skipping ping`);
      if (process.env.GITHUB_OUTPUT) {
        appendFileSync(process.env.GITHUB_OUTPUT, `count=0\n`);
      }
      return;
    }
    submitUrls = diffUrls(prevUrls, nextUrls);
    console.log(`diff mode: ${submitUrls.length} changed URL(s) between ${args.prev} and ${args.next}`);
  }

  if (submitUrls.length > 0) {
    console.log('URLs:');
    for (const url of submitUrls) console.log(`  ${url}`);
  }

  if (process.env.GITHUB_OUTPUT) {
    appendFileSync(process.env.GITHUB_OUTPUT, `count=${submitUrls.length}\n`);
  }

  if (args.dryRun) {
    console.log(`[dry-run] would submit ${submitUrls.length} URL(s); no POST made`);
    return;
  }

  if (submitUrls.length === 0) {
    console.log('no changed URLs, skipping POST');
    return;
  }

  for (const urlList of chunk(submitUrls, CHUNK_SIZE)) {
    await postChunk(urlList);
  }
}

main().catch((err) => {
  console.error(`indexnow-ping failed: ${err.message}`);
  process.exit(1);
});
